### ISSUE TITLE
Error while starting p2pool

### ISSUE THREAD

**Issue by SHlNOBI** [jtoomim/p2pool#32]
Following is the log of the error:
What  might be the issue? 

`root@nf:/home/p2pool# python run_p2pool.py --testnet
2019-07-13 10:05:52.332821 p2pool (version 16.0-160-g9b5938a)
2019-07-13 10:05:52.333124 
2019-07-13 10:05:52.333432 Testing bitcoind P2P connection to '127.0.0.1:18333'...
2019-07-13 10:05:52.338334     ...success!
2019-07-13 10:05:52.338552 
2019-07-13 10:05:52.338791 Testing bitcoind RPC connection to 'http://127.0.0.1:18332/' with username 'shiobi'...
Error while checking Bitcoin connection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/p2pool/p2pool/bitcoin/helper.py", line 14, in check
    if not (yield net.PARENT.RPC_CHECK(bitcoind)):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/p2pool/p2pool/bitcoin/networks/bitcoin_testnet.py", line 18, in <lambda>
    (yield bitcoind.rpc_getinfo())['testnet']
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -32601 Method not found

`

**Comment by jtoomim** [comment]
Is this the master branch with Bitcoin Core 0.18?

**Comment by SHlNOBI** [comment]
Yes. Its 0.18. I ran on testnet , regtest and mainnet and the result is same.

**Comment by SHlNOBI** [comment]
It worked.  I previously disabled  "listen" on  bitcoind. Thanks.
