### ISSUE TITLE
exceptions.KeyError: 'ismine'

### ISSUE THREAD

**Issue by arruah** [jtoomim/p2pool#40]
After run this command  
`pypy run_p2pool.py --net bitcoincash --bitcoind-config-path /opt/bch/bitcoin.conf --allow-obsolete-bitcoind`
I got the error:  
`Fatal error:
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
--- <exception caught here> ---
  File "/home/kamren/p2pool/p2pool/main.py", line 138, in main
    if not res['isvalid'] or not res['ismine']:
exceptions.KeyError: 'ismine'
`

**Comment by jtoomim** [comment]
I suspect that if you specify a default mining address with the `--address xxxxxxxxxxx` command-line option, this problem will go away. But this does look like a bug, so I'm leaving the issue open until it's fixed.

**Comment by arruah** [comment]
When I try `pypy run_p2pool.py --net bitcoincash --bitcoind-config-path /opt/bch/bitcoin.conf --coinbtext="p2pcash.kz" --logfile=p2pool.log --address 212.19.134.154`  I got the error  
`run_p2pool.py: error: error parsing address: ValueError('invalid addr',)`

**Comment by jtoomim** [comment]
no, `--address` is for a Bitcoin Cash address, not an IP address. E.g. `--address qp2g5zsxs2238m0s593j8yce2k2l42qhfcvwnylmxh`.

**Comment by mansilladev** [comment]
Was the original issue reported here fixed in https://github.com/jtoomim/p2pool/pull/65 ?

**Comment by jtoomim** [comment]
Seems like it.
