### ISSUE TITLE
Merged urls fails

### ISSUE THREAD

**Issue by red0bear** [jtoomim/p2pool#52]
i was suppose to check merged urls feature but it always fail wen start calling a error on message.

**Comment by red0bear** [comment]
Traceback (most recent call last):
  File "pypy-VER-PLATFORM/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "pypy-VER-PLATFORM/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "pypy-VER-PLATFORM/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "pypy-VER-PLATFORM/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "pypy-VER-PLATFORM/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "pypy-VER-PLATFORM/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -32601 Method not found

**Comment by red0bear** [comment]
I made little work around and see getauxblock is not used anymore. But dont know much details.
