### ISSUE TITLE
Error when finding an AUX block

### ISSUE THREAD

**Issue by ikolubr** [jtoomim/p2pool#61]
@jtoomim ,
Do you have any idea why I'm getting this error when finding an AUX block? I just updated my p2pool to latest and now it is giving me that error.

Thank you,

```
Error while processing merged mining POW:
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/d
efer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/root/p2pool/p2pool/util/jsonrpc.py", line 85, in _handle
    result = yield method_meth(*list(preargs) + list(params))
  File "/root/p2pool/p2pool/bitcoin/stratum.py", line 134, in rpc_submit
    result = got_response(header, worker_name, coinb_nonce, self.target)
  File "/root/p2pool/p2pool/bitcoin/worker_interface.py", line 139, in <lambda>
    lambda header, user, coinbase_nonce, pseudoshare_target: handler(header, user, pack.IntType(self._my_bits).pack(nonce) + coinbase_nonce, pseudoshare_target),
--- <exception caught here> ---
  File "/root/p2pool/p2pool/work.py", line 488, in got_response
    sub_meth = aux_work['merged_proxy'].rpc.getauxblock
  File "/root/p2pool/p2pool/util/jsonrpc.py", line 50, in __getattr__
    raise AttributeError('%r object has no attribute %r' % (self.__class__.__name__, attr))
exceptions.AttributeError: 'Proxy' object has no attribute 'rpc'
```

**Comment by ikolubr** [comment]
Thank you. Problem solved.
