### ISSUE TITLE
BCH don't start

### ISSUE THREAD

**Issue by Anandraj-Singh** [jtoomim/p2pool#64]
Hello! Can't run p2pool with Bitcoin Cash. Here is the log on startup:
```
# pypy run_p2pool.py --net bitcoincash --bitcoind-config-path /root/.bitcoin/bitcoin.conf
2022-06-13 23:16:10.734485 p2pool (version 16.0-200-g9eaae22)
2022-06-13 23:16:10.734740
2022-06-13 23:16:10.734939 Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username 'bch'...
2022-06-13 23:16:10.946342     ...success!
2022-06-13 23:16:10.946568     Current block hash: 643c01c8ffe2d6d55667e3de5d059f4fa1b3e07e2b332cb
2022-06-13 23:16:10.946725     Current block height: 744356
2022-06-13 23:16:10.946864
2022-06-13 23:16:10.947050 Testing bitcoind P2P connection to '127.0.0.1:8333'...
2022-06-13 23:16:10.951640     ...success!
2022-06-13 23:16:10.951795
2022-06-13 23:16:10.951979 Determining payout address...
2022-06-13 23:16:10.952167     Getting payout address from bitcoind...
Error getting payout address from bitcoind:
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/root/p2pool/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/p2pool/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -32601 Method not found
```
Can you help me?

**Comment by jtoomim** [comment]
It looks like there is some issue with getting an address from BCHN. Try adding a default payout address via the `--address` command-line option.

**Comment by Anandraj-Singh** [comment]
Thank you! Started! 
Please tell me where can I get an interface similar to this one http://sha256.p2p-spb.xyz:9338/static/ ?

**Comment by Anandraj-Singh** [comment]
What could be causing this?

**Comment by jtoomim** [comment]
That's probably just an `inv` for a Compact Block (value=4) on the BCH p2p network. I'm guessing that happens right after a new block is found on the BCH network, right? 

It's harmless and safe to ignore.

**Comment by Anandraj-Singh** [comment]
I have another question: if I run my node p2pool with a donation option, Will you receive a block reward or someone else?

**Comment by jtoomim** [comment]
The donations go to Forrest Voigt (forrestv), the original author of p2pool. As far as I have seen, he hasn't moved any of his donations since 2013, and currently has 17.7 BTC, 17.0 BCH, and 344 LTC sitting around.

**Comment by Anandraj-Singh** [comment]
I started my node p2pool with donation 1%. Let him(forrestv) be paid, the main thing is that the project p2pool lives and develops. Thanks for the help!

**Comment by jtoomim** [comment]
FWIW, forrestv's last contributions were from 2016.

**Comment by kr1z1s** [comment]
> The donations go to Forrest Voigt (forrestv), the original author of p2pool. As far as I have seen, he hasn't moved any of his donations since 2013, and currently has 17.7 BTC, 17.0 BCH, and 344 LTC sitting around.

Yes and BSV, XEC and many many others. Wherever it pubkey is used
