### ISSUE TITLE
exceptions.ValueError: gentx doesn't match hash_link

### ISSUE THREAD

**Issue by ghost** [jtoomim/p2pool#66]
I've created my own altcoin and setting up p2pool for scrypt mining. Everything works great until a block gets mined and I get this error. Also the miner only get's 0.1 coin and not 20. Been trying to get around this for days now. Appriciate if you guys could take the time to help me out :)

"
2022-07-12 20:39:44.211862 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2022-07-12 20:39:44.212049  Local: 12530H/s in last 15.5 seconds Local dead on arrival: ~0.0% (0-8%) Expected time to share: 1.4 minutes
2022-07-12 20:40:14.213224 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2022-07-12 20:40:14.213432  Local: 10116H/s in last 45.5 seconds Local dead on arrival: ~0.0% (0-6%) Expected time to share: 1.7 minutes
2022-07-12 20:40:44.214071 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2022-07-12 20:40:44.214278  Local: 13059H/s in last 1.3 minutes Local dead on arrival: ~0.0% (0-5%) Expected time to share: 1.3 minutes
2022-07-12 20:41:14.215882 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2022-07-12 20:41:14.216086  Local: 13328H/s in last 1.8 minutes Local dead on arrival: ~0.0% (0-5%) Expected time to share: 1.3 minutes
2022-07-12 20:41:23.496091 
2022-07-12 20:41:23.496219 GOT BLOCK FROM MINER! Passing to bitcoind! ed0a3adec61d58ac430ea25040525aaf24445f308c7aadfc3774c5884bf88352
2022-07-12 20:41:23.496270 
2022-07-12 20:41:23.500576 GOT SHARE! MThiBVZ1xAEYSvB6i1WXR5BbQYSsRY9pHV 4bf88352 prev xxxxxxxx age 115.82s
2022-07-12 20:41:23.501659 88754209086101587363432403941069444047867804914959720749306888963007345768855 42114609786524032990359427111505060556914516875841598301516162347366901126883
2022-07-12 20:41:23.501795 {'version': 1, 'tx_ins': [{'previous_output': None, 'sequence': None, 'script': '\x02\x84\x08'}], 'tx_outs': [{'value': 0, 'script': 'j$\xaa!\xa9\xed\x92\xac\x07\xc7\xb9\xe0\x08\xef\xfd\xe0\xe4u0d\xf22\x8b\x1c\x8c\xd3\xd0\xb4\x88\xf4\xbf\x1b\xba\x8c\xb93\x8c6'}, {'value': 10000000, 'script': 'v\xa9\x14\xd981\xb1\xa8\x0f\xc1\xaeM\x06M\x92\xfa\xe4\xeb\xd5\xa4\x15\x9c_\x88\xac'}, {'script': 'A\x04\xff\xd0=\xe4Jn\x11\xb9\x91\x7f:)\xf9D2\x83\xd9\x87\x1c\x9dt>\xf3\r^\xdd\xcd7\tKd\xd1\xb3\xd8\t\x04\x96\xb52Vxk\xf5\xc8)2\xec#\xc3\xb7M\x9f\x05\xa6\xf9Z\x8bU)5&VfK\xac', 'value': 1990000000}, {'value': 0, 'script': 'j(NFZZ4\xa5\x94Y\x01!\t\xbc\xa7%\xe29\xb2\x90x\xd8\xbd\xb1\x19[\x9bk6m\x94s8\xdf\x07\x00\x00\x00\x00\x00\x00\x00'}], 'lock_time': 0, 'marker': 0, 'flag': 1, 'witness': [['[P2Pool][P2Pool][P2Pool][P2Pool]']]}
Share check failed: ed0a3adec61d58ac430ea25040525aaf24445f308c7aadfc3774c5884bf88352 -> 0000000000000000000000000000000000000000000000000000000000000000
Traceback (most recent call last):
  File "/home/ubuntu/p2pool/p2pool/bitcoin/worker_interface.py", line 139, in <lambda>
    lambda header, user, coinbase_nonce, pseudoshare_target: handler(header, user, pack.IntType(self._my_bits).pack(nonce) + coinbase_nonce, pseudoshare_target),
  File "/home/ubuntu/p2pool/p2pool/work.py", line 530, in got_response
    self.node.set_best_share()
  File "/home/ubuntu/p2pool/p2pool/node.py", line 327, in set_best_share
    best, desired, decorated_heads, bad_peer_addresses, self.punish= self.tracker.think(self.get_height_rel_highest, self.get_height, self.bitcoind_work.value['previous_block'], self.bitcoind_work.value['bits'], self.known_txs_var.value, self.feecache)
  File "/home/ubuntu/p2pool/p2pool/data.py", line 745, in think
    if self.attempt_verify(share, block_abs_height_func, known_txs, feecache):
--- <exception caught here> ---
  File "/home/ubuntu/p2pool/p2pool/data.py", line 723, in attempt_verify
    share.gentx = share.check(self, known_txs, block_abs_height_func=block_abs_height_func, feecache=feecache)
  File "/home/ubuntu/p2pool/p2pool/data.py", line 557, in check
    raise ValueError('''gentx doesn't match hash_link''')
exceptions.ValueError: gentx doesn't match hash_link

2022-07-12 20:41:23.511306 > Block submittal result: False (u'duplicate') Expected: True
2022-07-12 20:41:23.512931 New work! Share diff: 0.00 Block value: 20.00 TWTC (0 tx, 0 kB)
2022-07-12 20:41:44.216756 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2022-07-12 20:41:44.216938  Local: 12131H/s in last 2.3 minutes Local dead on arrival: ~0.0% (0-5%) Expected time to share: 1.5 minutes
2022-07-12 20:42:14.217614 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2022-07-12 20:42:14.217767  Local: 9932H/s in last 2.8 minutes Local dead on arrival: ~0.0% (0-5%) Expected time to share: 1.9 minutes
"

**Comment by ghost** [comment]
Nobody cares to help. Moved on to other working pool.

**Comment by ikolubr** [comment]
> Nobody cares to help. Moved on to other working pool.

Which working pool, if you don't mind me asking.
