### ISSUE TITLE
Error about IMMUTABLE_BLOCKS

### ISSUE THREAD

**Issue by ikolubr** [jtoomim/p2pool#67]
Hi guys,
Getting this error while mining Litecoin/DOGE.
It shows up, screws the hashing for some time then it goes away.

```
Unhandled Error
Traceback (most recent call last):
  File "/p2pool/main.py", line 723, in run
    reactor.run()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/p2pool/bitcoin/stratum.py", line 75, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/p2pool/bitcoin/worker_interface.py", line 132, in get_work
    desired_pseudoshare_target, worker_ip, *args)
  File "/p2pool/work.py", line 370, in get_work
    base_subsidy=self.node.net.PARENT.SUBSIDY_FUNC(self.current_work.value['height']),
  File "/p2pool/data.py", line 197, in generate_transaction
    if all_transaction_weight + this_weight + 4*80 + cls.gentx_weight + 2000 > net.BLOCK_MAX_WEIGHT and not net.IMMUTABLE_BLOCKS:
exceptions.AttributeError: 'module' object has no attribute 'IMMUTABLE_BLOCKS'
```

Thank you for supporting p2pool,
Igor Almeida

**Comment by jtoomim** [comment]
This is on `rawtx`?

**Comment by ikolubr** [comment]
> This is on `rawtx`?

Correct: ```On branch rawtx```

Thank you,

**Comment by jtoomim** [comment]
Can you tell me what's on line 36 of your `p2pool/networks/litecoin.py` file?

Can you tell me the output of `git status`?

**Comment by ikolubr** [comment]
Line 36 of ```p2pool/networks/litecoin.py```:
```BLOCK_MAX_WEIGHT = 4000000```

Output of ```git status```:
```
On branch rawtx
Your branch is up to date with 'origin/rawtx'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    web-static/d3.v2.min.js
	deleted:    web-static/graphs.html
	modified:   web-static/index.html
	deleted:    web-static/share.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	web-static/.editorconfig
	web-static/.gitignore
	web-static/LICENSE
	web-static/README.md
	web-static/css/
	web-static/img/
	web-static/js/

no changes added to commit (use "git add" and/or "git commit -a")
```

The changes and untracked files are the different front end that I use.

Thank you @jtoomim

**Comment by jtoomim** [comment]
Oops, sorry. Line 38 of `p2pool/networks/litecoin.py`.

**Comment by jtoomim** [comment]
Also, `git branch -v` please.

**Comment by ikolubr** [comment]
A-ha! That is weird...
line 36 was the last line of the file... so I went into the repo and checked the file, which has ```IMMUTABLE_BLOCKS = True``` in it. Mine, for whatever reason didn't!!!
I added manually to see if the error doesn't show up.

Output of ```git branch -v``` before I manually added the line above:
```
master ece15b0 Merge pull request #65 from mansilladev/ismine-attr-fix
* rawtx  29fc6fc Stratum fixes:  - zero-pad extranonce1 and 2 to fix odd-length string issue;  - support extranonce1 (1 byte) to support Avalon 1246;  - use "null" instead of a random ID for pushed stratum messages (notify, set_difficulty)
```

Thank you

**Comment by ikolubr** [comment]
Fixed.
